server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/virtual_slime?serverTimezone=UTC&characterEncoding=utf-8
  mail:
    host: stmp.126.com
    username: virtualslime@126.com
    password: SNIMWDUGRCSKRZQU
    protocol: stmp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis-plus:
  type-enums-package: com.virtualSlime.Enum